spring:
  application:
    name: shikiri-tasks
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/shikiri}
    username: ${DATABASE_USERNAME:shikiri}
    password: ${DATABASE_PASSWORD:shikiri123321}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: tasks
  jpa:
    properties:
      hibernate:
        default_schema: tasks

management:
  endpoints:
    web:
      base-path: /tasks/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

springdoc:
  api-docs:
    path: /tasks/v3/api-docs
  swagger-ui:
    path: /tasks/swagger-ui.html
  version: 3.0.0