apiVersion: v1
kind: Service
metadata:
    name: tool
    labels:
        name: tool
spec:
    type: NodePort
    ports:
        - port: 8080
        targetPort: 8080
        protocol: TCP
    selector:
        app: tool
