server:
    port: 8080

spring:
    application:
        name: tasks
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
        username: ${POSTGRES_USERNAME:postgres}
        password: ${POSTGRES_PASSWORD:Post123321}
        driver-class-name: org.postgresql.Driver
    flyway:
        baseline-on-migrate: true
        schemas: tasks
    jpa:
        properties:
            hibernate:
                default_schema: tasks
    redis:
        host: ${REDIS_HOST}
        port: ${REDIS_PORT}

management:
    endpoints:
        web:
        base-path: /tasks/actuator
        exposure:
            include: ['*', 'prometheus']

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://${DISCOVERY_HOST}:8761/eureka/

springdoc:
    api-docs:
        path: /tasks/v3/api-docs
    swagger-ui:
        path: /tasks/swagger-ui.html
    version: 3.0.0